name: Daily Random Choice

on:
  schedule:
    - cron: '30 18 * * *'  # UTC 18:30 = 北京时间 2:30
  workflow_dispatch:

jobs:
  generate-choice:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码（公开仓库无需 token）
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # 保留凭据供后续 git push 使用

      # 2. 设置 Python 环境
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. 运行脚本
      - name: Run Script
        run: python random_choice.py

      # 4. 提交并推送文件
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/choices/
          git commit -m "Auto: Add today's choice"
          git pull --rebase origin main  # 解决可能的冲突
          git push origin HEAD:main
