name: Daily Random Choice

on:
  schedule:
    - cron: '50 18 * * *'  # UTC 18:30 = 北京时间 2:30
  workflow_dispatch:

jobs:
  generate-choice:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 关键！授予写入权限
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run Script
        run: python random_choice.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/choices/
          git commit -m "Auto: Add today's choice"
          git pull --rebase origin main
          git push origin HEAD:main
